(load "elscreen" "Elscreen" t)
(global-set-key "\C-m" 'newline-and-indent)
(global-set-key "\C-h" 'delete-backward-char)
(global-set-key "\C-ch" 'help-for-help)
;(global-set-key "\C-c\C-m" 'execute-extended-command)
;(global-set-key "\C-w" 'backward-kill-word)
;(global-set-key "\C-c\C-k" 'kill-region)
;(global-set-key "\C-ck" 'kill-region)
;(global-set-key "\C-c\C-s" 'eshell)
;(global-set-key "\C-c\C-b" 'electric-buffer-list)
;(global-set-key "\C-c\C-i" 'indent-region)
;(global-set-key "\C-c\C-j" 'eval-print-last-sexp)
;(global-set-key "\C-cj" 'eval-print-last-sexp)
(global-set-key "\C-z " 'elscreen-next)
;(global-set-key "\C-z\C-z" 'elscreen-swap)
(global-set-key "\C-zn" 'elscreen-create)
;(global-set-key [C-tab] 'PC-lisp-complete-symbol)
;(global-set-key (kbd "s-o") 'other-window)
;(global-set-key (kbd "s-]") 'next-buffer)
;(global-set-key (kbd "s-[") 'previous-buffer)
;(global-set-key (kbd "s-0") 'delete-window)
;(global-set-key (kbd "s-1") 'delete-other-windows)
;(global-set-key (kbd "s-2") 'split-window-verticaly)
;(global-set-key (kbd "s-3") 'split-window-horizontally)
;(global-set-key (kbd "s-k") 'kill-this-buffer)
;(global-set-key (kbd "M-s-o") 'other-frame)
;(global-set-key (kbd "M-s-0") 'delete-frame)
;(global-set-key (kbd "M-s-2") 'make-frame-command)
